# Generated by Django 5.2.8 on 2026-04-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_id_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('bicycle', 'Bicicleta'), ('motorcycle', 'Motocicleta')], default='bicycle', max_length=20, verbose_name='Método de Envío'),
        ),
    ]
